// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rydoouyepjvnqbwnfvxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5ZG9vdXllcGp2bnFid25mdnh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzODk1NjQsImV4cCI6MjA1Nzk2NTU2NH0.L9lrV-dPaL0YL9PR6GDL8iAMreIfyveAvax27vm35uE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);